name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bayesian-optimization=3.1.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - expat=2.7.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - joblib=1.5.2=py312h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py312hacdc0fc_0
  - mkl_fft=2.1.1=py312h8fe796d_0
  - mkl_random=1.3.0=py312h505adc9_0
  - ncurses=6.5=h7934f7d_0
  - numpy=2.0.2=py312h64c44e4_2
  - numpy-base=2.0.2=py312he1678cf_2
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - scikit-learn=1.7.2=py312h505adc9_0
  - scipy=1.16.3=py312h33bc11c_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - ale-py==0.11.2
    - attrs==25.4.0
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.2.1
    - cloudpickle==3.1.1
    - contourpy==1.3.3
    - cycler==0.12.1
    - farama-notifications==0.0.4
    - filelock==3.19.1
    - fonttools==4.60.1
    - fsspec==2025.9.0
    - gymnasium==1.2.1
    - idna==3.11
    - jinja2==3.1.6
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - markupsafe==2.1.5
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - msgpack==1.1.2
    - networkx==3.5
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.6.77
    - opencv-python==4.12.0.88
    - pillow==11.3.0
    - protobuf==6.33.0
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.3
    - ray==2.51.1
    - referencing==0.37.0
    - requests==2.32.5
    - rpds-py==0.28.0
    - six==1.17.0
    - sympy==1.14.0
    - torch==2.9.0+cu126
    - torchvision==0.24.0+cu126
    - triton==3.5.0
    - typing-extensions==4.15.0
    - urllib3==2.5.0
prefix: /nfs/home/eze9611/.conda/envs/myenv
